#+OPTIONS: "\n:t
#+OPTIONS: ^:{}
#+OPTIONS: _:{}
#+TITLE: Friends

* friend with
  why do i friend with thost people.
  我怎么会和这些人交上朋友

* butter up
  i just want to butter her up first.
  butter sb up 用花言巧语讨好某人

* be way too
  she's way too emotional.
  she's way too young for him.
  太(与去掉way意思一样)

* get past
  we have to get past this.
  我们必须忘记它（8.15）

* freaked out
  i'm all freaked out.
  我被你们吓着了

* let's just say / footage
  well, let's just say it's ironic how footage of someone being born can make you want to kill yourself.
  这么说吧，讽刺的是看某人出生的镜头能使人想自杀

* screw you
  screw you gays, you don't have to do it.
  去你的

* i got to go
  我得走了

* on good terms
  it's jsut that we didn't really end things on such good terms.
  良好的关系

* benefit of the doubt
  you're comming on a little strong, but i'm going to give you the benefit of the doubt.
  假定某人无罪（因证据不足）

* it meant a lot to me
  这对我意义重大

* meant to be
  it wasn't meant to be. 本不该如此
  命中注定

* pearls of wisdom
  This is such a great party! 35 years, very impressive, do you guys have any pearls of wisdom?
  至理名言

* who's who
  you collective dating record reads like the who's who of human crap.
  名人录

* dial down
  we're dial down the crazy.

* blow off
  please don't blow her off. 不要和她分手

#+BEGIN_HTML
<script src="../../Layout/JS/disqus-comment.js"></script>
<div id="disqus_thread">
</div>
#+END_HTML
