#+OPTIONS: ^:{} _:{} num:t toc:t \n:t
#+INCLUDE: "../../template-toc.org"
#+title:
* crush/flattered
  crush 暗恋的人
  flatter奉承，谄媚->flattered 高兴的，感到荣幸的
#+begin_example
Today, my crush asked to use my phone so he could Google something. Flattered that he wanted to use my phone, I agreed. After he was done, he handed it back with a weird look. I later realized he had found himself in my top searches. FML
#+end_example
* horde
  a horde of 一大群
#+begin_example
Today, the iPhone app I downloaded that plays cricket noises during the night, has attracted a horde of actual crickets into my bedroom. FML
#+end_example
* sprain
  sprain 扭伤 sprain ankle扭伤脚踝
#+begin_example
Today, I sprained my ankle trying to prove that I can walk in high heels. FML
#+end_example
* euphemism
  euphemism 委婉语
  euphemistic=euphemious 委婉的 euphemize 委婉地说 
#+begin_example
Today, my boyfriend invited me over to "play with his lizard." After excitedly rushing across town, I realized this wasn't a euphemism, he actually bought an Iguana. FML
#+end_example
* sanitizer/armpit/intensify/stench/vaguely
  sanitize 对...进行消毒杀菌->sanitizer 食品防腐剂；消毒杀菌剂->hand sanitizer洗手液
  armpit 腋下 ->armpit odor
  intense 紧张的，密集的->intensify 增加，加剧，强化
  stench 恶臭 stink 臭味 stinking 臭的
  vague 模糊的，含糊的 vaguely
#+begin_example
Today, I decided to use hand sanitizer to mask the smell of my armpits at work. Not only did it intensify the stench, my boss thinks I have a drinking problem, because I vaguely smelled of alcohol. I was too embarrassed to explain. FML
#+end_example
* ignition/retrieve
  ignite 点燃，点火->ignition 点火装置 ignition key 点火钥匙（汽车术语）
  retrieve 取回
#+begin_example
Today, while I was leaving the grocery store, I realized my ignition key was missing from my pocket. After searching the car and retracing my steps, I walked all the way home. Later, when we went to retrieve the car, the key was sitting in plain sight on the passenger seat. FML
#+end_example
* constipation
  constipate (v)便秘，呆滞 -> constipation (n)便秘
#+begin_example
Today, while having sex with my girlfriend in the bathroom, we heard a knock at the door, then her father's voice. I had to fake constipation noises until he left. FML
#+end_example
* snuck
  sneak 偷偷地做，溜； ->snuck 过去式
#+begin_example
Today, I snuck out to go see my girlfriend. When I got to her house, I left my bike out front and we went on a nice walk around the block. We passed a homeless-looking woman going the opposite way. About ten minutes later, the same woman passed us, on my bike. FML
#+end_example
* bigot
  bigot 顽固的人，偏执的人->bigoted 顽固的 ->bigotry 顽固
* dogma
  n 教义/教条
  dogmatic 教条的，武断的，傲慢专断的－>dogmatist教条主义者
  doctrine 教条/教义/主义
* I don't know you from Adam.
  我不认识你。
* mellow
  mellow 成熟的/圆润的/柔和的 | 使成熟
#+begin_example
In general, Tommy is a very shy orangutan. But since the iPad has been introduced, his behavior has mellowed in a way and he has gotten more accustomed to being near people. 
#+end_example
* enclosure
  enclosure 附件/围墙/笼子
#+begin_example
But he would watch from the back of his enclosure as the zoo keepers worked with the other orangutans.
#+end_example
* attest
  provide or serve as a clear evidence 证明/表明
  attest (to) sth 证明了某件事
  #+begin_example
  His numerous drawings of babies attest to his fascination with them.
  His handling of the crisis attested to his strength of character.
  Her outstanding abilities were attested by her rapid promotion. 
  #+end_example
* penisula
  半岛
  #+begin_example
  Many are looking forward to calmer days on the Korean peninsula. 
  #+end_example
* -logue
  表谈话
  dialogue 对话（两个人）
  monologue 独白（一个人）
* inebriated
  adj intoxicated/drunk
** inebriate
   v make drunk/become drunk
   =intoxicate
* retarded
  limited or delayed in intellectual and/or emotional development, characterized by mental retardation
  adj 智力迟钝的
  mental retardation 智力迟钝
** retard
   make sth slow or late/hinder 使放慢或阻碍 
* striptease
  脱衣舞
** strip
   v take off clothes脱衣
** tease
   n/v
   1. make fun of 取笑
   2. tempt sexually 挑逗
* ham
  火腿 a ham sandwich火腿三明治
* SWAT
  Special Weapon And [[file:Amercia-TheStoryOfUs-WW2.org::tactical][Tactics]] 特殊武器与战术.
  拥有先进技术战术手段的反暴力、反恐怖特别执法单位。 
* pervert
  v 误用滥用/（人/心理）堕落/变坏
  n 变态
* brunette
  深色发肤的人
* arrogant
  傲慢的
* resort to
  make use of sth for help采取某种行动作为紧急措施
  #+begin_example
  If negotiations fail we shall have to resort to strike action. 假若谈判失败, 我们就采取罢工行动.
  #+end_example
* derail
  使火车/电车出轨；使事情偏离原来的方向
  #+begin_example
  derailing the conversation into flaming matches
  #+end_example
* persecute
  ~ sb for sth因为信仰不同而对其加以迫害
  #+begin_example
  the phrasing here is persecuting.
  #+end_example
* refute
  反驳 prove to be wrong
  #+begin_example
  refute a claim, a theory, an argument 驳斥某要求、理论、论点
  #+end_example
* rebuke
  指责 express sharp or severe disapproval to sb, esp officially
  rebuke sb for sth
  #+begin_example
  My boss rebuked me for coming to work late. 我的上司指摘我上班迟到.
  #+end_example
* crackpot
  crazy,nut,weirdo疯子/怪人
* elaborate
  v Add more details concerning what has already been said 更详细地描述
  adj 详细的/复杂的
* pedestrian
  someone who travels on foot徒步旅行者
* pessimism
  悲观
  派生词：
  | pessimistic     | 悲观的     |
  | pessimistically | 悲观地        |
  | pessimist       | 悲观主义者 |
  反：optimism 乐观的
  | optimistic | adj        |
  | optimist   | 乐观主义者 |
* penetrate
  v 插入、渗入、遍布、洞察/发现、被（他人）理解领悟（to be fully understood by sb.）
  #+begin_example
  The heavey rain had penetrated right through his coat.
  He penetrated their thoughts.
  I explained the problem to him several times but it didn't seem to penerate.
  #+end_example
  penetration n
* mourn
  v (因丧失某人或某物)哀悼悲痛
  mourn for/over sb/sth
  #+begin_example
  He mourned for his dead child for many years. 
  #+end_example
  mourner 哀悼者（参加葬礼的亲朋）
* allegedly
  allege
  v state sth as a fact but without proof 声称
  #+begin_example
  The prisoner alleged that he was at home on the night of the crime.
  #+end_example
  alleged
  adj 被控告的/据称的
  #+begin_example
  the alleged conspirators（同谋）. 
  #+end_example
  allegedly
  adv 据说地
  #+begin_example
  He was allegedly a leading participant in the coup attempt.
  #+end_example
* sublease
  lease
  v rent租
  n 租约
  #+begin_example
  He leased the site to a local company.
  #+end_example
  sublease=sublet转租
* almighty
  =omnipotent万能的
* hot-button
  政治敏感话题
* hothead
  冲动的人
* splutter
  v 咳呛声/气急败坏地说
  #+begin_example
  "How dare you?" she spluttered.
  #+end_example
* What's the buzz?
  最近的话题
* cease and desist
  警告（正式地）
  desist =cease =stop
* obnoxious
  adj extremely unpleasant
* hooray
  叫好声/万岁
* chore
  unpleasant job
  #+BEGIN_EXAMPLE
  If you read your news from an NNTP server that's far away, the network latencies may make reading articles a chore. 
  #+END_EXAMPLE
* credential
  证书/凭据
  certificate
* caveat
  warning
