#+OPTIONS: "\n:t
#+OPTIONS: ^:{}
#+OPTIONS: _:{}
#+TITLE: S05.05
* All systems go, if you catch my drift
  all systems go 各系统准备就绪、一切正常、万事具备
  catch my drift 听懂我说的话
* Something is obviously bugging you. What is it?
  bug 困扰
* I just can't believe you signed up the space program without even talking to me.
  without doing sth
  without even doing 甚至没有做某件事
* Bernadette, an opportunit has come up that impacts both of us, and I'd like to discuss it.
  an opportunity has come up 机会来了
* I've been offer a chance to go up to Internation Space Station for three weeks. What are your thoughts on that?
  be offered an chance 被给了个机会
  What are your thoughts on that? =>What do you think about it? 你怎么想的
* If going to space means that much to you, I'll never say another word about it.
  say another word about it.不会反对
* Over my dead body my son goes into outer space.
  我死也不会让我儿子去外太空的。
* with all my heart.
  真心的
* behind my back
  背着我
* I just did what I did because I love you so much, and the thought of losing you is more that I can handle.
  more than I can handle. 我承受不来。
