#+OPTIONS: ^:{} _:{} num:t toc:t \n:t
#+include "../../template-toc.org"
#+title: STL: Algorithm

* copy
#+begin_src c++
template< class InputIterator, class OutputIterator >
OutputIterator copy( InputIterator first, InputIterator last, OutputIterator d_first );
#+end_src
  所做的操作类似为 *d_first = *first, *(d_first+1)=*(first+1) ...
* copy_backward
#+begin_src c++
template< class BidirectionalIterator1, class BidirectionalIterator2 >
BidirectionalIterator2 copy_backward( BidirectionalIterator1 first,
                                      BidirectionalIterator1 last,
                                      BidirectionalIterator2 d_last );
#+end_src
  所做的操作类似为 *d_last=*last, *(d_last-1)=*(last-1),...
  与copy的区别在于指定目的区域的末地址，而copy指定的是首地址。且拷贝顺序不同。
  此函数适用于拷贝区间与目的区间存在交叉，且从前拷贝到后的情况，例如：1-10区间拷贝到5-15，如果用copy函数则 *有可能* 会毁坏数据.
  同理如果从5-15拷贝到1-10如果用copy_backward则 *有可能* 毁坏数据。

  *为什么是有可能?*
  因为两个copy根据其操作对象的不同采用不同的行为，如果是原始指针则采用 *memmove* 方法而此函数由于借助了其它辅助空间所以不会产生覆盖。
#+begin_src c++
     int ary[] = {0,1,2,3,4,5,6};
     copy(ary, ary+3, ary+1);
     for_each(ary, ary+sizeof(ary)/sizeof(int), display<int>()); // 0 0 1 2 4 5 6
#+end_src
  表面上看应该会产生覆盖所以结果应该是 0 0 0 0 4 5 6，但其实结果是 0 0 1 2 4 5 6，原因就是因为原始指针调用的是 memmove.
  由于vector内部typedef value_type* iterator;所以其迭代器也是原始指针，所以也调用的是memmove,不必担心覆盖的问题。
#+begin_src c++
     int ary[] = {0,1,2,3,4,5,6};
     vector<int> ivec(ary, ary+sizeof(ary)/sizeof(int));
     copy(ivec.begin(), ivec.begin()+3, ivec.begin()+1);
     for_each(ivec.begin(), ivec.end(), display<int>()); // 0 0 1 2 4 5 6
#+end_src
  list由于其迭代器非原始指针，故最终调用的是循环复制，所以会造成覆盖。
#+begin_src c++
     list<int> List(ary, ary+sizeof(ary)/sizeof(int));
     typedef list<int>::iterator listiter;
     listiter first=List.begin();
     advance(first,2);
     listiter last=List.end();
     advance(last, -2);
     listiter result=List.begin();
     advance(result,4);
     copy(first, last, result);
     for_each(List.begin(), List.end(), display<int>());        //0 1 2 3 2 3 2 3 2
#+end_src
* copy_n (C++11)
#+begin_src c++
template< class InputIterator, class Size, class OutputIterator>
OutputIterator copy_n(InputIterator first, Size count, OutputIterator result);
#+end_src
* accumulate
#+begin_src c++
template< class InputIterator, class T >
T accumulate( InputIterator first, InputIterator last, T init );
template< class InputIterator, class T, class BinaryOperation >
T accumulate( InputIterator first, InputIterator last, T init,
              BinaryOperation op );
#+end_src
  1. 返回对[first,last)之间的元素和init求和结果。
  2. 与1的区别在于使用op函数而非求和函数。
#+begin_src c++
     int ary[] = {0,1,2,3,4,5,6,7,8};
     // 0+0+1+2...
     cout<<accumulate(ary, ary+sizeof(ary)/sizeof(int), 0)<<endl; // 36
     // 0-0-1-2-3-...
     cout<<accumulate(ary, ary+sizeof(ary)/sizeof(int), 0, minus<int>())<<endl; // -36
#+end_src
* inner_product
#+begin_src c++
template< class InputIterator1, class InputIterator2, class T >
T inner_product( InputIterator1 first1, InputIterator1 last1,
                 InputIterator2 first2, T value );

template<
    class InputIterator1,
    class InputIterator2,
    class T,
    class BinaryOperation1,
    class BinaryOperation2
> T inner_product( InputIterator1 first1, InputIterator1 last1,
                   InputIterator2 first2, T value,
                   BinaryOperation1 op1,
                   BinaryOperation2 op2 );
#+end_src
  1. [first1, last1)与first2开始last1-first1个构成的区间对应的元素相乘后相加。
  2. 1中的相乘改为op2，相加改为op1.
#+begin_src c++
     int ip1[] = {1,2,3};
     int ip2[] = {2,3,4,5,6};
     cout<<inner_product(ip1,ip1+3,ip2, 100)<<endl; // 100+1*2+2*3+3*4=120
     cout<<inner_product(ip1,ip1+3,ip2, 100, minus<int>(), plus<int>())<<endl; // 100-(1+2)-(2+3)-(3+4)=85
#+end_src
* partial_sum
#+begin_src c++
template< class InputIterator, class OutputIterator >
OutputIterator partial_sum( InputIterator first, InputIterator last, OutputIterator d_first );

template< class InputIterator, class OutputIterator, class BinaryOperation >
OutputIterator partial_sum( InputIterator first, InputIterator last, OutputIterator d_first,
                            BinaryOperation op );
#+end_src
  所做的操作为：
#+begin_example
*(d_first)   = *first;
*(d_first+1) = *first + *(first+1);
*(d_first+2) = *first + *(first+1) + *(first+2);
*(d_first+3) = *first + *(first+1) + *(first+2) + *(first+3);
...
#+end_example
  第2个版本中用op操作替换+.
#+begin_src c++
     int ip2[] = {2,3,4,5,6};
     partial_sum(ip2, ip2+5, ostream_iterator<int>(cout, " ")); // 2 5 9 14 20
     partial_sum(ip2, ip2+5, ostream_iterator<int>(cout, " "), minus<int>()); // 2 -1 -5 -10 -16
#+end_src
* adjacent_difference
  与partial_sum相似。只是操作相邻元素。
#+begin_example
*(d_first)   = *first;
*(d_first+1) = (*first+1) - *(first);
*(d_first+2) = (*first+2) - *(first+1);
*(d_first+3) = (*first+3) - *(first+2);
#+end_example

#+begin_src c++
     int ip2[] = {2,3,4,5,6};
     adjacent_difference(ip2, ip2+5, ostream_iterator<int>(cout, " ")); // 2 1 1 1 1
     adjacent_difference(ip2, ip2+5, ostream_iterator<int>(cout, " "), plus<int>()); // 2 5 7 9 11
#+end_src
* equal
#+begin_src c++
template< class InputIterator1, class InputIterator2 >
bool equal( InputIterator1 first1, InputIterator1 last1, 
            InputIterator2 first2 );

template< class InputIterator1, class InputIterator2, class BinaryPredicate >
bool equal( InputIterator1 first1, InputIterator1 last1, 
            InputIterator2 first2, BinaryPredicate p );
#+end_src
  [first1,last1)之间的元素是否与first2开始的同等个数的区间对应元素相同。如果first2开始的元素个数没有first1到last1之间的多则结果不确定。
  第2个版本可以自定义比较操作，默认是相等。
#+begin_src c++
     int ip1[] = {1,2,3};
     int ip2[] = {1,2,3,4,5,6};
     cout<<equal(ip1,ip1+3,ip2)<<endl; // 1
     cout<<equal(ip1,ip1+3,ip2+1)<<endl; // 0
     cout<<equal(ip1,ip1+3,ip2+1, less<int>())<<endl; // 1
#+end_src
* fill
#+begin_src c++
template< class ForwardIterator, class T >
void fill( ForwardIterator first, ForwardIterator last, const T& value );
#+end_src
  用value填充区间[first,last).
* fill_n
#+begin_src c++
template< class OutputIterator, class Size, class T >
void fill_n( OutputIterator first, Size count, const T& value );        //before c++11

template< class OutputIterator, class Size, class T >
OutputIterator fill_n( OutputIterator first, Size count, const T& value ); //C++11
#+end_src
  填充指定位置开始的指定个数元素，C++11中返回值与advance(first,count);相同。
* iter_swap
#+begin_src c++
template< class ForwardIterator1, class ForwardIterator2 >
void iter_swap( ForwardIterator1 a, ForwardIterator2 b );
#+end_src
  交换两个迭代器的内容。调用的是swap函数。
* swap
#+begin_src c++
template< class T >
void swap( T& a, T& b );

template< class T, size_t N >
void swap( T (&a)[N], T (&b)[N]);       //c++11
#+end_src
  swap可交换的对象包含了几乎所有的泛型对象：vector,list,queue...
  C++11的swap调用的是swap_range(a, a+N, b);
* swap_range
#+begin_src c++
template< class ForwardIterator1, class ForwardIterator2 >
ForwardIterator2 swap_ranges( ForwardIterator1 first1, ForwardIterator1 last1, ForwardIterator2 first2 )
#+end_src
  交换[first1,last1)与first2开始的区间。
  内部调用的是iter_swap。
* lexicographical_compare
#+begin_src c++
template< class InputIterator1, class InputIterator2 >
bool lexicographical_compare( InputIterator1 first1, InputIterator1 last1,
                              InputIterator2 first2, InputIterator2 last2 );

template< class InputIterator1, class InputIterator2, class Compare >
bool lexicographical_compare( InputIterator1 first1, InputIterator1 last1,
                              InputIterator2 first2, InputIterator2 last2,
                              Compare comp );
#+end_src
  以词典序排序。
  先比较 min((last1-first1),(last2-first2)) 个，如果比较出来则返回否则第1个区间短则返回真否则返回假。
* mismatch
#+begin_src c++
template< class InputIterator1, class InputIterator2 >
std::pair<InputIterator1,InputIterator2>
    mismatch( InputIterator1 first1,
              InputIterator1 last1,
              InputIterator2 first2 );

template< class InputIterator1, class InputIterator2, class BinaryPredicate >
std::pair<InputIterator1,InputIterator2>
    mismatch( InputIterator1 first1,
              InputIterator1 last1,
              InputIterator2 first2,
              BinaryPredicate p );
#+end_src
  返回第一次不匹配的第1个区间迭代器和第2个区间迭代器构成的pair.
* set_union
#+begin_src c++
template< class InputIterator1, class InputIterator2, class OutputIterator >
OutputIterator set_union( InputIterator1 first1, InputIterator1 last1,
                          InputIterator2 first2, InputIterator2 last2,
                          OutputIterator d_first );
template< class InputIterator1, class InputIterator2,
          class OutputIterator, class Compare >
OutputIterator set_union( InputIterator1 first1, InputIterator1 last1,
                          InputIterator2 first2, InputIterator2 last2,
                          OutputIterator d_first, Compare comp );
#+end_src
  欲合并的两个集合必须是已经排序好的，故 set, multiset可以但 unordered_set, unordered_multiset不可用。
  第1版本默认是less排序。
  若某元素a在S1 [first1,last)中出现n次，在S2 [first2,last2)中出现 m次，则结果中出现 =max(n,m)= 次，其中S1中的全部出现在结果中，S2中出现 =max(n-m,0)= 次。
  结果是稳定的，即相对次序不变。
* set_difference
  结果中a出现次数为 =max(n-m,0)= ，全部来自S1
* set_intersection
  结果中a出现次数为 =min(n,m)= ，全部来自S1
* set_symmetric_difference
  结果中a出现次数为 =|n-m|= ，若 n>m则S1中的最后n-m个a为结果的a，若n<m则S2中最后的m-n个a为结果中的a。
* adjacent_find
#+begin_src c++
template< class ForwardIterator >
ForwardIterator adjacent_find( ForwardIterator first, ForwardIterator last );
template< class ForwardIterator, BinaryPredicate p >
ForwardIterator adjacent_find( ForwardIterator first, ForwardIterator last, BinaryPredicate p );
#+end_src
  返回连续相同元素的第1个元素的迭代器。第2个版本定义了“相同“含义。
* count, count_if
#+begin_src c++
template< class InputIterator, class T >
typename iterator_traits<InputIterator>::difference_type
    count( InputIterator first, InputIterator last, const T &value );

template< class InputIterator, class UnaryPredicate >
typename iterator_traits<InputIterator>::difference_type
    count_if( InputIterator first, InputIterator last, UnaryPredicate p );
#+end_src
  统计指定元素在某区间出现个数，第2个版本定义了“相同“含义。
* find, find_if, find_if_not(C++11)
#+begin_src c++
template< class InputIterator, class T >
InputIterator find( InputIterator first, InputIterator last, const T& value );
template< class InputIterator, class UnaryPredicate >
InputIterator find_if( InputIterator first, InputIterator last, UnaryPredicate p );
template< class InputIterator, class UnaryPredicate >
InputIterator find_if_not( InputIterator first, InputIterator last, UnaryPredicate q );
#+end_src
  查找某元素在某区间的第1次出现的位置，如果没有查找到则返回last.
  if定义了“相同“含义。
  if_not 查找第1个相同的元素。
* find_end
#+begin_src c++
template< class ForwardIterator1, class ForwardIterator2 >
ForwardIterator1 find_end( ForwardIterator1 first, ForwardIterator1 last,
                           ForwardIterator2 s_first, ForwardIterator2 s_last );
template< class ForwardIterator1, class ForwardIterator2, class BinaryPredicate >
ForwardIterator1 find_end( ForwardIterator1 first, ForwardIterator1 last,
                           ForwardIterator2 s_first, ForwardIterator2 s_last, BinaryPredicate p );
#+end_src
  查找 [s_first, s_last)作为[first, last)的子序列最后出现的位置，如果不是子序列则返回 last
#<<find_first_of>>
* find_first_of
#+begin_src c++
template< class ForwardIterator1, class ForwardIterator2 >
ForwardIterator1 find_first_of( ForwardIterator1 first, ForwardIterator1 last,
                                ForwardIterator2 s_first, ForwardIterator2 s_last );

template< class ForwardIterator1, class ForwardIterator2, class BinaryPredicate >
ForwardIterator1 find_first_of( ForwardIterator1 first, ForwardIterator1 last,
                                ForwardIterator2 s_first, ForwardIterator2 s_last, BinaryPredicate p );
#+end_src
  [s_first, s_last)中任意一个元素第1次在[first,last)中出现的位置，如果任何元素都没有在[first,last)中出现则返回last.
* for_each
#+begin_src c++
template< class InputIterator, class UnaryFunction >
UnaryFunction for_each( InputIterator first, InputIterator last, UnaryFunction f );
#+end_src
  对[first,last)中每个元素都施加函数f，可以通过解引用来修改相应的元素（此时最好用transform函数）。
* transform
#+begin_src c++
template< class InputIterator, class OutputIterator, class UnaryOperation >
OutputIterator transform( InputIterator first1, 
                          InputIterator last1,
                          OutputIterator d_first, 
                          UnaryOperation unary_op );
template< class InputIterator1, class InputIterator2, class OutputIterator, class BinaryOperation >
OutputIterator transform( InputIterator1 first1, 
                          InputIterator1 last1,
                          InputIterator2 first2, 
                          OutputIterator d_first, 
                          BinaryOperation binary_op );
#+end_src
  1. 对[first1,last1)中每个元素作用一元函数f，结果保存在d_first开始的组件中（d_first开始的组件大小必须>=last1-first1).
  2. 以[first1,last1)中每个元素和以first2开头的相应元素做为二元函数f的参数，结果保存在d_first中。
* generate, generate_n
#+begin_src c++
template< class ForwardIterator, class Generator >
void generate( ForwardIterator first, ForwardIterator last, Generator g );

template< class OutputIterator, class Size, class Generator >
void generate_n( OutputIterator first, Size count, Generator g );
#+end_src     
  用生成器g返回值依次替换[first,last)中每个元素/替换以first开始的count个元素。
#+begin_src c++
class incf_by_one
{
private:
     static int __count;
public:
     int operator()(){return __count++;}
};
int incf_by_one::__count = 0;

int main(int argc, char *argv[])
{
     vector<int> ivec(10);
     generate(ivec.begin(), ivec.end(), incf_by_one());
     for_each(ivec.begin(), ivec.end(), display<int>()); // 0 1 2 3 4 5 6 7 8 9
     return 0;
}

#+end_src
* includes
#+begin_src c++
template< class InputIterator1, class InputIterator2 >
bool includes( InputIterator1 first1, InputIterator1 last1,
               InputIterator2 first2, InputIterator2 last2 );
template< class InputIterator1, class InputIterator2 >
bool includes( InputIterator1 first1, InputIterator1 last1,
               InputIterator2 first2, InputIterator2 last2, Compare comp );
#+end_src
  *已排序* 的集合[first2,last2)是否是 *已排序* 的集合[first1,last1)的子集。（不一定是连续出现的）
#+begin_src c++
     int tp1[] = {1,2,3,4};
     int tp2[] = {1,3};
     cout<<includes(tp1,tp1+4,tp2,tp2+2)<<endl; // 1
#+end_src
* max_element, min_element
#+begin_src c++
template< class ForwardIterator > 
ForwardIterator max_element( ForwardIterator first, ForwardIterator last );
template< class ForwardIterator, class Compare >
ForwardIterator max_element( ForwardIterator first, ForwardIterator last, 
                             Compare comp );
#+end_src
  返回一个区间中最大/最小元素。
* merge, inplace_merge
#+begin_src c++
template< class InputIterator1, class InputIterator2, class OutputIterator >
OutputIterator merge( InputIterator1 first1, InputIterator1 last1,
                      InputIterator2 first2, InputIterator2 last2 
                      OutputIterator d_first );
template< class InputIterator1, class InputIterator2, class OutputIterator, class Compare>
OutputIterator merge( InputIterator1 first1, InputIterator1 last1,
                      InputIterator2 first2, InputIterator2 last2 
                      OutputIterator d_first, Compare comp );
#+end_src
  *已排序* 的两个区间合并后保存到d_first开始的区间内。默认是less，可以自定义比较函数comp.
#+begin_src c++
template< class BidirectionalIterator >
void inplace_merge( BidirectionalIterator first,
                    BidirectionalIterator middle,
                    BidirectionalIterator last );
template< class BidirectionalIterator, class Compare>
void inplace_merge( BidirectionalIterator first,
                    BidirectionalIterator middle,
                    BidirectionalIterator last,
                    Compare comp );
#+end_src
  两个 *已排序* 的连续区间合并为一个区间。
* partition, stable_partition
#+begin_src c++
template< class BidirectionalIterator, class UnaryPredicate >
BidirectionalIterator partition( BidirectionalIterator first, BidirectionalIterator last,
                                 UnaryPredicate p );
template< class BidirectionalIterator, class UnaryPredicate >
BidirectionalIterator stable_partition( BidirectionalIterator first, BidirectionalIterator last,
                                        UnaryPredicate p );
#+end_src
  将区间内符合条件p的元素放在区间开始位置，不符合的放到后面。
  前者是不稳定（即不保证次序不变），后者是稳定的，即次序保持不变。
* remove, remove_if, remove_copy, remove_copy_if
#+begin_src c++
template< class ForwardIterator, class T >
ForwardIterator remove( ForwardIterator first, ForwardIterator last, 
                        const T& value );
template< class ForwardIterator, class UnaryPredicate >
ForwardIterator remove_if( ForwardIterator first, ForwardIterator last, 
                           UnaryPredicate p );

template< class InputIterator, class OutputIterator, class T >
OutputIterator remove_copy( InputIterator first,
                            InputIterator last,
                            OutputIterator d_first,
                            const T& value );
template< class InputIterator, class OutputIterator, class UnaryPredicate >
OutputIterator remove_copy_if( InputIterator first,
                               InputIterator last,
                               OutputIterator d_first,
                               UnaryPredicate p );
#+end_src
  前两个删除区间中符合条件的/指定的元素，删除时靠移动元素，故新尾端和旧尾端之间的元素不变。
  后两个是将区间删除后的结果拷贝到指定位置。
#+begin_src c++
     int tp1[] = {1,2,3,4};
     vector<int> ivec(tp1, tp1+4);
     remove(ivec.begin(), ivec.end(), 3);
     for_each(ivec.begin(), ivec.end(), display<int>()); // 1 2 4 4
#+end_src  
* replace, replace_if, replace_copy, replace_copy_if
#+begin_src c++
template< class ForwardIterator, class T >
void replace( ForwardIterator first, ForwardIterator last, const T& old_value, const T& new_value );

template< class ForwardIterator, class UnaryPredicate, class T >
void replace_if( ForwardIterator first, ForwardIterator last, UnaryPredicate p, const T& new_value );

template< class InputIterator, class OutputIterator, class T >
OutputIterator replace_copy( InputIterator first, InputIterator last, OutputIterator d_first, const T& old_value, const T& new_value );

template< class InputIterator, class OutputIterator, class UnaryPredicate, class T >
OutputIterator replace_copy_if( InputIterator first, InputIterator last, OutputIterator d_first, UnaryPredicate p, const T& new_value );
#+end_src
  将区间中所有指定元素/符合条件的元素替换成指定元素。
  前两个原地修改。
  后两个将作用结果保存到指定位置。
* reverse, reverse_copy
#+begin_src c++
template< class BidirectionalIterator >
void reverse( BidirectionalIterator first, BidirectionalIterator last );
#+end_src
  逆转指定区间。
* rotate, rotate_copy
#+begin_src c++
template< class ForwardIterator >
void rotate( ForwardIterator first, ForwardIterator middle, ForwardIterator last );
template< class ForwardIterator, class OutputIterator >
OutputIterator rotate_copy( ForwardIterator first, ForwardIterator middle, ForwardIterator last, OutputIterator d_first );
#+end_src
  将[first,middle)与[middle,last)两个区间交换位置。
* search
#+begin_src c++
template< class ForwardIterator1, class ForwardIterator2 >
ForwardIterator1 search( ForwardIterator1 first, ForwardIterator1 last, ForwardIterator2 s_first, ForwardIterator2 s_last );
template< class ForwardIterator1, class ForwardIterator2, class BinaryPredicate >
ForwardIterator1 search( ForwardIterator1 first, ForwardIterator1 last, ForwardIterator2 s_first, ForwardIterator2 s_last, BinaryPredicate p );
#+end_src
  [s_first, s_last)区间第1次在[first,last)中出现的位置，如果区间没有在[first,last)中出现则返回last.
  与 [[find_first_of]] 的区别在：后者只需要满足任意一个元素出现即可，而前者必须所有元素完全匹配。
* search_n
#+begin_src c++
template< class ForwardIterator, class Size, class T >
ForwardIterator1 search_n( ForwardIterator first, ForwardIterator last, Size count, const T& value );
template< class ForwardIterator, class Size, class T, class BinaryPredicate >
ForwardIterator1 search_n( ForwardIterator first, ForwardIterator last, Size count, const T& value, BinaryPredicate p );
#+end_src
  连续count个value在[first,last)中出现的位置。
* unique, unique_copy
#+begin_src c++
template< class ForwardIterator >
ForwardIterator unique( ForwardIterator first, ForwardIterator last );
template< class ForwardIterator, class BinaryPredicate >
ForwardIterator unique( ForwardIterator first, ForwardIterator last, BinaryPredicate p );
template< class ForwardIterator, class OutputIterator >
ForwardIterator unique_copy( ForwardIterator first, ForwardIterator last, OutputIterator d_first );
template< class ForwardIterator, class OutputIterator, class BinaryPredicate >
ForwardIterator unique_copy( ForwardIterator first, ForwardIterator last, OutputIterator d_first, BinaryPredicate p );
#+end_src
  删除 *连续* 的重复元素。
