#+OPTIONS: ^:{} _:{} num:t toc:t \n:t
#+INCLUDE "../../template-toc.org"
#+SETUPFILE: "../../extension.org"
#+title:Ubuntu Trick
* 备份源
  通过命令 =add-apt-repository= 添加的源都保存在 =/etc/apt/source.list.d/= 中的list结尾的文件中，可以将它们备份起来然后在新系统上恢复从而节省时间。
  =cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list > ~/sources.list=
* 备份包
  将当前系统安装包保存到文件中 =sudo dpkg --get-selections > list.txt= ,在新系统上可以用 =sudo dpkg --set-selections < list.txt= 来安装。
* 命令行批量安装字体
  将当前目录下所有字体拷贝到 /usr/share/font/myfont 中.
#+begin_example
  find . -name "*.ttf" -exec sudo cp {} /usr/share/fonts/myfont/ \;
#+end_example
  然后执行 =sudo mkfontscale && sudo mkfontdir && sudo fc-cache -fv= 。
  这样字体便安装好了，可以通过 =fc-list|grep font-name= 来验证。
* 切换键盘布局
  System-Preferences-Keyboard Layouts 新添加一个layout
  设置切换layout的快捷键：Options-Keys 
* 将gif转换成avi
  :PROPERTIES:
  :CUSTOM_ID: giftoavi
  :END:
  首先安装imagemagick，之后
  #+begin_example
  convert logo.gif logo%02d.jpg   
  #+end_example
  生成好多jpg文件，其中%02d和C语言中意思相同，表logo后跟两位数，如果gif的帧数超过两位数则应该考虑log%03d.jpg.
  之后安装ffmpeg
  #+begin_example
  ffmpeg -r 25 -i logo%02d.jpg -y -an new.avi
  #+end_example
  1. -r表帧速率，默认是25.值越小生成avi时间越长（播放速度越慢）。
  2. -i表输入文件，同理logo%02d.jpg 表logo后跟2位数再后跟.jpg
  3. -y表输出文件如果与当前文件重名则选择覆盖掉
  4. -an表不使用录音

  另外
  #+begin_example
  convert -strip test.gif test.jpg  
  #+end_example
  可以将gif每帧生成一个jpg文件。
* 解决evince中文乱码
  1. 安装poppler-data: =sudo apt-get install poppler-data=
  2. =rm /etc/fonts/conf.d/49-sansserif.conf=
